# Generated by Django 4.2.8 on 2023-12-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='category',
            new_name='categories',
        ),
    ]
