# Generated by Django 4.2.8 on 2023-12-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_category_meal_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
    ]
