# Generated by Django 4.2.8 on 2023-12-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_restaurant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='meals', related_query_name='meal', to='core.restaurant'),
            preserve_default=False,
        ),
    ]
